require("varzil.plugins.comment")
require("varzil.plugins.nvim-tree")
require("varzil.plugins.lualine")
--require("packer_compiled")
--require("varzil.plugins.telescope")
-- This telescope doesn't work
require("varzil.plugins.nvim-cmp")
require("varzil.plugins.lsp.mason")
require("plugin.lspsage")
require("varzil.plugins.lsp.lspconfig")
require("varzil.plugins.lsp.null-ls")
require("varzil.plugins.autopairs")
require("varzil.plugins.treesitter")
require("varzil.plugins.gitsigns")
require("varzil.plugins-setup")
require("varzil.core.options")
require("varzil.core.keymaps")
require("varzil.core.colorscheme")
